# Generated by Django 5.0 on 2025-11-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0006_emailoptout'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnconfirmedVote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vote_hash', models.CharField(max_length=100)),
                ('vote_tinyhash', models.CharField(max_length=50, null=True, unique=True)),
                ('cast_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
